---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "./data_bags"
  roles_path: "./roles"
  environments_path: "./environments"
  client_rb:
    audit_mode: :disabled

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: ubuntu-16.04
      box_url: https://atlas.hashicorp.com/bento/boxes/ubuntu-16.04/versions/2.3.4/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: ubuntu-14.04
    driver_config:
      box: ubuntu-14.04
      box_url: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.3.4/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: centos-6.8
    driver_config:
      box: bento-centos-6.8
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-6.8/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: centos-7.3
    driver_config:
      box: bento-centos-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/centos-7.3/versions/2.3.2/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: oracle-6.8
    driver_config:
      box: bento-oracle-6.8
      box_url: https://atlas.hashicorp.com/bento/boxes/oracle-6.8/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89
  - name: oracle-7.3
    driver_config:
      box: bento-oracle-7.3
      box_url: https://atlas.hashicorp.com/bento/boxes/oracle-7.3/versions/2.3.1/providers/virtualbox.box
      require_chef_omnibus: 12.14.89

suites:
   - name: cm
     run_list:
       - recipe[cm]
